id: P008141
initial_creation_type: ocr
source_metadata:
  id: bdr:W29633
  title: བོད་ཀྱི་སྤྲུལ་སྐུའི་རྣམ་བཤད་ལས་འཕྲོས་པའི་བདེན་གཏམ་དཔྱིད་ཀྱི་ཕོ་ཉ
  author: ''
  volumes:
    12348f8d7fc94c4a89354b84adf9a49e:
      image_group_id: I5540
      title: ''
      volume_number: 1
      total_pages: 88
ebook_metadata:
  title: བོད་ཀྱི་སྤྲུལ་སྐུའི་རྣམ་བཤད་ལས་འཕྲོས་པའི་བདེན་གཏམ་དཔྱིད་ཀྱི་ཕོ་ཉ
  author: ''
  sku: P008141
  cover: cover.jpg
  layers:
  - pagination
