id: I0D7D16BD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T05:18:44+00:00'
last_modified: '2022-06-09T04:47:18.832772+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29633
  title: བོད་ཀྱི་སྤྲུལ་སྐུའི་རྣམ་བཤད་ལས་འཕྲོས་པའི་བདེན་གཏམ་དཔྱིད་ཀྱི་ཕོ་ཉ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '9664':
      image_group_id: I5540
      title: ''
      total_pages: 88
      order: 1
      base_file: 9664.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
